#!/bin/csh -f
set CGCUTE = $cwd
cd CUTEr_interface
cp ../cg_user.h  $CUTEST/include
cp cg_descent.pro sdcg_descent.pro $CUTER/build/prototypes
cp cg_descentma.c  $CUTER/common/src/tools
cd ..
make purge
make
cp cg_descent.o  $MYCUTER/double/bin
cd $CUTER/common/src/tools
gcc -O3 -lm -c cg_descentma.c
cp cg_descentma.o $MYCUTER/double/bin
cd $MYCUTER/bin
sed -f $MYCUTER/double/config/script.sed $CUTER/build/prototypes/cg_descent.pro > cg_descent
sed -f $MYCUTER/double/config/script.sed $CUTER/build/prototypes/sdcg_descent.pro > sdcg_descent
chmod a+x cg_descent sdcg_descent
cd $CGCUTE
rehash
